[error] /home/michael/giant/common/src/main/scala/utils/attempt/package.scala:21:79: type mismatch; [error]  found   : Seq[(play.api.libs.json.JsPath, scala.collection.Seq[play.api.libs.json.JsonValidationError])] (in scala.collection) [error]  required: Seq[(play.api.libs.json.JsPath, Seq[play.api.libs.json.JsonValidationError])]                  (in scala.collection.immutable) [error]     def toAttempt = jsResult.asEither.toAttempt(jsonError => JsonParseFailure(jsonError)) [error]                                                                               ^ [error] one error found [error] (common / Compile / compileIncremental) Compilation failed [error] Total time: 2 s, completed 8 Oct 2022, 19:56:20