upgrading bouncycastle after a runtime missing field error for sphincsPlus_shake_256 (bumping to latest version 1.79 doesn't work as it does not have the field). Including javax.mail as a dependency - not including it resulted in NoClassDefFoundError: javax/mail/Part