[error] /home/michael/giant/backend/app/services/manifest/Neo4jManifest.scala:126:48: value hasKeyOrFailure is not a member of List[org.neo4j.driver.v1.Record] [error]       results <- summary.list().asScala.toList.hasKeyOrFailure("c", NotFoundFailure(s"Collection '$collection' does not exist.")) [error]                                                ^